SET TEMAS=(CLASSICO AMARELO CHUVA BRAPRET PRETBRA PRETMAG PRETAZUL PRETVERDE CIANOGRAD CACHORRO)

SET PASTATEMAS="BIN\TEMAS"

XCOPY /Y SRC\GERATALHOS\GERATALHOS32.EXE BIN\
XCOPY /Y SRC\GERATALHOS\GERATALHOS64.EXE BIN\

XCOPY /Y MAQUINAS\TUDO.CSV BIN\LISTAOL.CSV

IF NOT EXIST %PASTATEMAS% (
  MKDIR %PASTATEMAS%
)

ECHO. 2>.\%PASTATEMAS%\DESC.INFO

FOR %%A IN %TEMAS% DO (
  CALL ZIP.CMD TEMAS\%%A\* %PASTATEMAS%\%%A
  IF EXIST %PASTATEMAS%\%%A.PRT DEL %PASTATEMAS%\%%A.PRT
  REN %PASTATEMAS%\%%A.ZIP %%A.PRT
  ECHO %%A.PRT>>.\%PASTATEMAS%\DESC.INFO
)


IF NOT EXIST BIN\MODELOS (
  MKDIR BIN\MODELOS
)
XCOPY /Y MODELOS\CONFIG.PRC BIN\MODELOS\
XCOPY /Y MODELOS\PRISMA.PRM BIN\MODELOS\