XCOPY /Y SRC\GERATALHOS\GERATALHOS.EXE BIN\

XCOPY /Y MAQUINAS\TUDO.CSV BIN\LISTAOL.CSV

IF NOT EXIST BIN\TEMAS (
  MKDIR BIN\TEMAS
)
CALL ZIP.CMD TEMAS\CLASSICO\* BIN\TEMAS\CLASSICO
REN BIN\TEMAS\CLASSICO.ZIP CLASSICO.PRT
ECHO Clássico,CLASSICO.PRT>.\BIN\TEMAS\DESC.INFO

CALL ZIP.CMD TEMAS\PRETMAG\* BIN\TEMAS\PRETMAG
REN BIN\TEMAS\PRETMAG.ZIP PRETMAG.PRT
ECHO Magenta no Preto,PRETMAG.PRT>>.\BIN\TEMAS\DESC.INFO

CALL ZIP.CMD TEMAS\PRETAZUL\* BIN\TEMAS\PRETAZUL
REN BIN\TEMAS\PRETAZUL.ZIP PRETAZUL.PRT
ECHO Azul no Preto,PRETAZUL.PRT>>.\BIN\TEMAS\DESC.INFO

IF NOT EXIST BIN\MODELOS (
  MKDIR BIN\MODELOS
)
XCOPY /Y MODELOS\CONFIG.PRC BIN\MODELOS\
XCOPY /Y MODELOS\PRISMA.PRM BIN\MODELOS\