IF NOT EXIST BIN\DADOS (
  MKDIR BIN\DADOS
)
XCOPY /Y MAQUINAS\DESC.INFO BIN\DADOS\
XCOPY /Y MAQUINAS\*.CSV BIN\DADOS\

IF NOT EXIST BIN\TEMAS (
  MKDIR BIN\TEMAS
)
CALL ZIP.CMD TEMAS\PRETMAG\* BIN\TEMAS\PRETMAG
REN BIN\TEMAS\PRETMAG.ZIP PRETMAG.PRT
ECHO Magenta no Preto,PRETMAG.PRT>.\BIN\TEMAS\DESC.INFO

IF NOT EXIST BIN\MODELOS (
  MKDIR BIN\MODELOS
)
XCOPY /Y MODELOS\CONFIG.PRC BIN\MODELOS\
XCOPY /Y MODELOS\PRISMA.PRM BIN\MODELOS\